version: "3.0"
services:
  api:
    image: api
    build: .
    ports:
      - '4000:4000'
    depends_on: 
      - db
  db:
    image: postgres
    build: ./db/
    ports:
      - '4001:4001'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: default-db
